branches:
  only:
    - master

dist: xenial
sudo: required

language: python
python: "3.7"

env:
  global:
    - DJANGO_SETTINGS_MODULE="backend.settings.dev"

install:
  - python -m pip install pipenv
  - pipenv install --dev

before_script:
  - python -m backend.manage makemigrations
  - python -m backend.manage migrate

script:
  - python -m backend.manage test
