branches:
  only:
    - master

dist: xenial
sudo: required

language: python
python: "3.7"

env:
  global:
    - DJANGO_SETTINGS_MODULE="backend.settings.dev"

install:
  - python -m pip install --user --upgrade pipenv
  - pipenv install --dev
  - pipenv shell

before_script:
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py test
